"""Generate the JSON Schema subset used here. No runtime validation is implied."""
from pathlib import Path
import json
import re
import sys

ROOT = Path(__file__).resolve().parents[1]


def ts(node):
    if '$ref' in node:
        return node['$ref'].rsplit('/', 1)[-1]
    if 'const' in node:
        return json.dumps(node['const'], ensure_ascii=False)
    if 'enum' in node:
        return ' | '.join(json.dumps(v, ensure_ascii=False) for v in node['enum'])
    for kind in ('oneOf', 'anyOf'):
        if kind in node:
            return ' | '.join('(' + ts(n) + ')' for n in node[kind])
    t = node.get('type')
    if t in ('integer', 'number'):
        return 'number'
    if t == 'null':
        return 'null'
    if t == 'boolean':
        return 'boolean'
    if t == 'string':
        return 'string'
    if t == 'array':
        return 'Array<' + ts(node['items']) + '>'
    if t == 'object':
        required = set(node.get('required', []))
        entries = []
        for name, child in node.get('properties', {}).items():
            key = name if re.fullmatch(r'[A-Za-z_$][A-Za-z0-9_$]*', name) else json.dumps(name)
            entries.append(key + ('' if name in required else '?') + ': ' + ts(child) + ';')
        extra = node.get('additionalProperties', False)
        if isinstance(extra, dict):
            entries.append('[key: string]: ' + ts(extra) + ';')
        elif extra is True:
            entries.append('[key: string]: unknown;')
        return '{ ' + ' '.join(entries) + ' }'
    raise ValueError('Unsupported schema node: ' + repr(node))


def generate():
    schema = json.loads((ROOT / 'contracts/mvp.schema.json').read_text(encoding='utf-8'))
    header = '// Generated by scripts/generate_types.py. DO NOT EDIT.\n'
    header += '// Runtime constraints remain in the JSON Schema and docs/RUNTIME.md.\n\n'
    return header + '\n\n'.join('export type ' + name + ' = ' + ts(body) + ';' for name, body in schema['$defs'].items()) + '\n'


if __name__ == '__main__':
    target = ROOT / 'contracts/mvp.types.ts'
    expected = generate()
    if '--check' in sys.argv:
        if not target.exists() or target.read_text(encoding='utf-8') != expected:
            raise SystemExit('Generated types are stale; run python scripts/generate_types.py')
    else:
        target.write_text(expected, encoding='utf-8')
